spring:
  application:
    name: api-gateway

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"